/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatToCookTodayRouteImport } from './routes/what-to-cook-today'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SavedRecipesRouteImport } from './routes/saved-recipes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoriteChefsRouteImport } from './routes/favorite-chefs'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeIdRouteImport } from './routes/recipe.$id'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as BlogIdRouteImport } from './routes/blog.$id'

const WhatToCookTodayRoute = WhatToCookTodayRouteImport.update({
  id: '/what-to-cook-today',
  path: '/what-to-cook-today',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRecipesRoute = SavedRecipesRouteImport.update({
  id: '/saved-recipes',
  path: '/saved-recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteChefsRoute = FavoriteChefsRouteImport.update({
  id: '/favorite-chefs',
  path: '/favorite-chefs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/favorite-chefs': typeof FavoriteChefsRoute
  '/login': typeof LoginRoute
  '/saved-recipes': typeof SavedRecipesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/what-to-cook-today': typeof WhatToCookTodayRoute
  '/blog/$id': typeof BlogIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipe/$id': typeof RecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/favorite-chefs': typeof FavoriteChefsRoute
  '/login': typeof LoginRoute
  '/saved-recipes': typeof SavedRecipesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/what-to-cook-today': typeof WhatToCookTodayRoute
  '/blog/$id': typeof BlogIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipe/$id': typeof RecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/favorite-chefs': typeof FavoriteChefsRoute
  '/login': typeof LoginRoute
  '/saved-recipes': typeof SavedRecipesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/what-to-cook-today': typeof WhatToCookTodayRoute
  '/blog/$id': typeof BlogIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipe/$id': typeof RecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/community'
    | '/discover'
    | '/favorite-chefs'
    | '/login'
    | '/saved-recipes'
    | '/signup'
    | '/sitemap.xml'
    | '/upload'
    | '/what-to-cook-today'
    | '/blog/$id'
    | '/profile/$username'
    | '/recipe/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/community'
    | '/discover'
    | '/favorite-chefs'
    | '/login'
    | '/saved-recipes'
    | '/signup'
    | '/sitemap.xml'
    | '/upload'
    | '/what-to-cook-today'
    | '/blog/$id'
    | '/profile/$username'
    | '/recipe/$id'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/community'
    | '/discover'
    | '/favorite-chefs'
    | '/login'
    | '/saved-recipes'
    | '/signup'
    | '/sitemap.xml'
    | '/upload'
    | '/what-to-cook-today'
    | '/blog/$id'
    | '/profile/$username'
    | '/recipe/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  CommunityRoute: typeof CommunityRoute
  DiscoverRoute: typeof DiscoverRoute
  FavoriteChefsRoute: typeof FavoriteChefsRoute
  LoginRoute: typeof LoginRoute
  SavedRecipesRoute: typeof SavedRecipesRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UploadRoute: typeof UploadRoute
  WhatToCookTodayRoute: typeof WhatToCookTodayRoute
  BlogIdRoute: typeof BlogIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  RecipeIdRoute: typeof RecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-to-cook-today': {
      id: '/what-to-cook-today'
      path: '/what-to-cook-today'
      fullPath: '/what-to-cook-today'
      preLoaderRoute: typeof WhatToCookTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-recipes': {
      id: '/saved-recipes'
      path: '/saved-recipes'
      fullPath: '/saved-recipes'
      preLoaderRoute: typeof SavedRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite-chefs': {
      id: '/favorite-chefs'
      path: '/favorite-chefs'
      fullPath: '/favorite-chefs'
      preLoaderRoute: typeof FavoriteChefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$id': {
      id: '/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  CommunityRoute: CommunityRoute,
  DiscoverRoute: DiscoverRoute,
  FavoriteChefsRoute: FavoriteChefsRoute,
  LoginRoute: LoginRoute,
  SavedRecipesRoute: SavedRecipesRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UploadRoute: UploadRoute,
  WhatToCookTodayRoute: WhatToCookTodayRoute,
  BlogIdRoute: BlogIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  RecipeIdRoute: RecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
